/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edd.Interfaz;

import EstructurasDeDatos.Busquedas;
import EstructurasDeDatos.Grafo;
import EstructurasDeDatos.Lista;
import EstructurasDeDatos.Nodo;
import EstructurasDeDatos.LecturaJson;
import org.graphstream.graph.*;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Luigi Lauricella
 */
public class MenuControles extends javax.swing.JFrame {

    public GraphStream graphstream;
    public Grafo grafo;
    public Lista lista;

    /**
     * Creates new form MenuControles
     */
    public MenuControles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JSONButton = new javax.swing.JButton();
        tButton = new javax.swing.JButton();
        tField = new javax.swing.JTextField();
        tLabel = new javax.swing.JLabel();
        MenuLabel = new javax.swing.JLabel();
        SucursalField = new javax.swing.JTextField();
        SucursalLabel = new javax.swing.JLabel();
        SucursalButton = new javax.swing.JButton();
        CoberturaLabel = new javax.swing.JLabel();
        DFSButton = new javax.swing.JButton();
        BFSButton = new javax.swing.JButton();
        CoberturaField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResultadosBusquedaArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        CoberturaArea = new javax.swing.JTextArea();
        CoverturaLabel = new javax.swing.JLabel();
        GrafoButton = new javax.swing.JButton();
        ParadasButton = new javax.swing.JButton();
        ParadasLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ParadasArea = new javax.swing.JTextArea();
        tLabel1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú de Controles");
        setBackground(new java.awt.Color(255, 153, 153));
        setForeground(java.awt.Color.darkGray);
        setResizable(false);

        JSONButton.setBackground(new java.awt.Color(0, 153, 102));
        JSONButton.setFont(new java.awt.Font("Swis721 Blk BT", 0, 14)); // NOI18N
        JSONButton.setForeground(new java.awt.Color(255, 255, 255));
        JSONButton.setText("  Cargar Json  ");
        JSONButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JSONButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSONButtonActionPerformed(evt);
            }
        });

        tButton.setBackground(new java.awt.Color(0, 153, 102));
        tButton.setFont(new java.awt.Font("Swis721 Blk BT", 0, 12)); // NOI18N
        tButton.setForeground(new java.awt.Color(255, 255, 255));
        tButton.setText("Cambiar");
        tButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tButtonActionPerformed(evt);
            }
        });

        tField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFieldActionPerformed(evt);
            }
        });

        tLabel.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tLabel.setText("  Establecer T  ");

        MenuLabel.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        MenuLabel.setForeground(new java.awt.Color(0, 153, 102));
        MenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuLabel.setText("  Menú de Control  ");
        MenuLabel.setToolTipText("");
        MenuLabel.setBorder(new javax.swing.border.MatteBorder(null));

        SucursalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SucursalFieldActionPerformed(evt);
            }
        });

        SucursalLabel.setFont(new java.awt.Font("Segoe UI Semilight", 2, 12)); // NOI18N
        SucursalLabel.setText("Colocar o eliminar sucursal por nombre");

        SucursalButton.setBackground(new java.awt.Color(0, 153, 102));
        SucursalButton.setFont(new java.awt.Font("Swis721 Blk BT", 0, 12)); // NOI18N
        SucursalButton.setForeground(new java.awt.Color(255, 255, 255));
        SucursalButton.setText("Cambiar");
        SucursalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SucursalButtonActionPerformed(evt);
            }
        });

        CoberturaLabel.setFont(new java.awt.Font("Segoe UI Semilight", 2, 12)); // NOI18N
        CoberturaLabel.setText("Seleccionar sucursal para búsqueda");

        DFSButton.setBackground(new java.awt.Color(0, 153, 102));
        DFSButton.setFont(new java.awt.Font("Swis721 Blk BT", 0, 12)); // NOI18N
        DFSButton.setForeground(new java.awt.Color(255, 255, 255));
        DFSButton.setText("DFS");
        DFSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DFSButtonActionPerformed(evt);
            }
        });

        BFSButton.setBackground(new java.awt.Color(0, 153, 102));
        BFSButton.setFont(new java.awt.Font("Swis721 Blk BT", 0, 12)); // NOI18N
        BFSButton.setForeground(new java.awt.Color(255, 255, 255));
        BFSButton.setText("BFS");
        BFSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFSButtonActionPerformed(evt);
            }
        });

        ResultadosBusquedaArea.setColumns(20);
        ResultadosBusquedaArea.setRows(5);
        jScrollPane1.setViewportView(ResultadosBusquedaArea);

        CoberturaArea.setColumns(20);
        CoberturaArea.setRows(5);
        jScrollPane2.setViewportView(CoberturaArea);

        CoverturaLabel.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        CoverturaLabel.setText("Sucursales recomendadas");

        GrafoButton.setBackground(new java.awt.Color(0, 153, 102));
        GrafoButton.setFont(new java.awt.Font("Swis721 Blk BT", 0, 14)); // NOI18N
        GrafoButton.setForeground(new java.awt.Color(255, 255, 255));
        GrafoButton.setText("  Mostrar grafo  ");
        GrafoButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GrafoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrafoButtonActionPerformed(evt);
            }
        });

        ParadasButton.setBackground(new java.awt.Color(0, 153, 102));
        ParadasButton.setFont(new java.awt.Font("Swis721 Blk BT", 0, 14)); // NOI18N
        ParadasButton.setForeground(new java.awt.Color(255, 255, 255));
        ParadasButton.setText("  Agregar línea de paradas  ");
        ParadasButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ParadasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParadasButtonActionPerformed(evt);
            }
        });

        ParadasLabel.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        ParadasLabel.setText("Lista de paradas nuevas");

        ParadasArea.setColumns(20);
        ParadasArea.setRows(5);
        ParadasArea.setText("Parada origen\nParadaNueva1\nParadaNueva2\n...\nParadaNuevaN");
        jScrollPane3.setViewportView(ParadasArea);

        tLabel1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tLabel1.setText("Resultados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(SucursalLabel)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(SucursalField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SucursalButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(CoverturaLabel)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addComponent(ParadasLabel)
                                .addGap(72, 72, 72))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tLabel1)
                        .addGap(118, 118, 118))))
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(JSONButton)
                .addGap(139, 139, 139)
                .addComponent(GrafoButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(MenuLabel)
                        .addGap(315, 315, 315))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(tLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tButton)))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(CoberturaField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addComponent(CoberturaLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(DFSButton)
                                .addGap(41, 41, 41)
                                .addComponent(BFSButton)))
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ParadasButton)
                        .addGap(306, 306, 306))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(MenuLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GrafoButton)
                            .addComponent(JSONButton))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SucursalLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SucursalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SucursalButton))))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CoverturaLabel)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ParadasLabel)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(ParadasButton)
                                .addGap(49, 49, 49))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(CoberturaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CoberturaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BFSButton)
                            .addComponent(DFSButton))
                        .addGap(43, 43, 43))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFieldActionPerformed

    }//GEN-LAST:event_tFieldActionPerformed

    private void SucursalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SucursalButtonActionPerformed
        CoberturaArea.setText("");
        if (grafo != null) {
            var red = graphstream.getGraphstream();
            String SucursalNombre = SucursalField.getText();
            Nodo NodoSeleccionado = grafo.SelecionarParada(SucursalNombre);
            Lista resultadosBFS = Busquedas.BFSSucursal(NodoSeleccionado, grafo.getT());
            CoberturaArea.setText(resultadosBFS.printList());
            if (NodoSeleccionado != null) {
                for (Node node : red) {
                    if (node.getId().equalsIgnoreCase(SucursalNombre)) {
                        String color = (String) node.getAttribute("ui.style");
                        if (grafo.SelecionarParada(SucursalNombre).getInfo().isSucursal() == false) {
                            if (color.equalsIgnoreCase("fill-color: blue;")) {
                                node.setAttribute("ui.style", "fill-color: purple;");
                            } else {
                                node.setAttribute("ui.style", "fill-color: red;");
                            }
                            grafo.SelecionarParada(SucursalNombre).getInfo().setSucursal(true);
                            JOptionPane.showMessageDialog(null, "La sucursal ha sido colocada exitosamente!", "Información", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            if (color.equalsIgnoreCase("fill-color: purple;")) {
                                node.setAttribute("ui.style", "fill-color: blue;");
                            } else {
                                node.setAttribute("ui.style", "fill-color: grey;");
                            }
                            grafo.SelecionarParada(SucursalNombre).getInfo().setSucursal(false);
                            JOptionPane.showMessageDialog(null, "La sucursal ha sido eliminada exitosamente!", "Información", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "ERROR, la parada seleccionada es invalida.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "ERROR, no cargaste un JSON antes.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        SucursalField.setText("");
    }//GEN-LAST:event_SucursalButtonActionPerformed

    private void JSONButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSONButtonActionPerformed
        try {
            grafo = new LecturaJson().LecturaJson();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "ERROR, tipo de dato invalido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JSONButtonActionPerformed

    private void tButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tButtonActionPerformed
        if (grafo != null) {
            try {
                int new_t = Integer.parseInt(tField.getText());
                grafo.setT(new_t);
                JOptionPane.showMessageDialog(null, "T ha sido cambiado a " + new_t + " exitosamente!", "Información", JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "ERROR, coloca un número entero.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "ERROR, no cargaste un JSON antes.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        tField.setText("");
    }//GEN-LAST:event_tButtonActionPerformed

    private void DFSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DFSButtonActionPerformed
        ResultadosBusquedaArea.setText("");
        if (grafo != null) {
            if (graphstream != null) {
                var red = graphstream.getGraphstream();
                String SucursalNombre = CoberturaField.getText();
                var NodoSeleccionado = grafo.SelecionarParada(SucursalNombre);
                if (NodoSeleccionado != null) {
                    for (Node node : red) {
                        String color = (String) node.getAttribute("ui.style");
                        if (color.equalsIgnoreCase("fill-color: blue;")) {
                            node.setAttribute("ui.style", "fill-color: grey;");
                        } else if (color.equalsIgnoreCase("fill-color: purple;")) {
                            node.setAttribute("ui.style", "fill-color: red;");
                        }
                    }
                    Lista resultados = Busquedas.DFS(NodoSeleccionado, grafo.getT());
                    for (Node node : red) {
                        for (int i = 0; i < resultados.count(); i++) {
                            Nodo aux = (Nodo) resultados.get(i);
                            String color = (String) node.getAttribute("ui.style");
                            if (node.getId().equalsIgnoreCase(aux.getInfo().getName())) {
                                if (color.equalsIgnoreCase("fill-color: red;")) {
                                    node.setAttribute("ui.style", "fill-color: purple;");
                                } else {
                                    node.setAttribute("ui.style", "fill-color: blue;");
                                }
                            }
                        }
                    }
                    CoberturaField.setText("");
                    ResultadosBusquedaArea.setText(resultados.printList());
                } else {
                    JOptionPane.showMessageDialog(null, "ERROR, la parada seleccionada es invalida.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "ERROR, muestra el grafo para observar los resultados.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "ERROR, no cargaste un JSON antes.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_DFSButtonActionPerformed

    private void BFSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFSButtonActionPerformed
        ResultadosBusquedaArea.setText("");
        if (grafo != null) {
            if (graphstream != null) {
                var red = graphstream.getGraphstream();
                String SucursalNombre = CoberturaField.getText();
                var NodoSeleccionado = grafo.SelecionarParada(SucursalNombre);
                if (NodoSeleccionado != null) {
                    for (Node node : red) {
                        String color = (String) node.getAttribute("ui.style");
                        if (color.equalsIgnoreCase("fill-color: blue;")) {
                            node.setAttribute("ui.style", "fill-color: grey;");
                        } else if (color.equalsIgnoreCase("fill-color: purple;")) {
                            node.setAttribute("ui.style", "fill-color: red;");
                        }
                    }
                    Lista resultados = Busquedas.BFS(NodoSeleccionado, grafo.getT());
                    for (Node node : red) {
                        for (int i = 0; i < resultados.count(); i++) {
                            Nodo aux = (Nodo) resultados.get(i);
                            String color = (String) node.getAttribute("ui.style");
                            if (node.getId().equalsIgnoreCase(aux.getInfo().getName())) {
                                if (color.equalsIgnoreCase("fill-color: red;")) {
                                    node.setAttribute("ui.style", "fill-color: purple;");
                                } else {
                                    node.setAttribute("ui.style", "fill-color: blue;");
                                }
                            }
                        }
                    }
                    CoberturaField.setText("");
                    ResultadosBusquedaArea.setText(resultados.printList());
                } else {
                    JOptionPane.showMessageDialog(null, "ERROR, la parada seleccionada es invalida.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "ERROR, muestra el grafo para observar los resultados.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "ERROR, no cargaste un JSON antes.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BFSButtonActionPerformed

    private void SucursalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SucursalFieldActionPerformed

    }//GEN-LAST:event_SucursalFieldActionPerformed

    private void GrafoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrafoButtonActionPerformed
        if (grafo != null) {
            GraphStream grafo1 = new GraphStream(grafo);
            graphstream = grafo1;
            grafo1.show();
            var red = graphstream.getGraphstream();
            for (Node node : red) {
                node.setAttribute("ui.style", "fill-color: grey;");
            }
        } else {
            JOptionPane.showMessageDialog(null, "ERROR, no cargaste un JSON antes.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_GrafoButtonActionPerformed

    private void ParadasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParadasButtonActionPerformed
        if (grafo != null) {
            String paradasNuevas = ParadasArea.getText();
            String[] paradas = paradasNuevas.split("\n");
            graphstream.agregarLinea(paradas);
            var red = graphstream.getGraphstream();
            for (Node node : red) {
                node.setAttribute("ui.style", "fill-color: grey;");
            }

        } else {
            JOptionPane.showMessageDialog(null, "ERROR, no cargaste un JSON antes.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ParadasButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuControles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuControles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuControles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuControles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuControles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BFSButton;
    private javax.swing.JTextArea CoberturaArea;
    private javax.swing.JTextField CoberturaField;
    private javax.swing.JLabel CoberturaLabel;
    private javax.swing.JLabel CoverturaLabel;
    private javax.swing.JButton DFSButton;
    private javax.swing.JButton GrafoButton;
    private javax.swing.JButton JSONButton;
    private javax.swing.JLabel MenuLabel;
    private javax.swing.JTextArea ParadasArea;
    private javax.swing.JButton ParadasButton;
    private javax.swing.JLabel ParadasLabel;
    private javax.swing.JTextArea ResultadosBusquedaArea;
    private javax.swing.JButton SucursalButton;
    private javax.swing.JTextField SucursalField;
    private javax.swing.JLabel SucursalLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton tButton;
    private javax.swing.JTextField tField;
    private javax.swing.JLabel tLabel;
    private javax.swing.JLabel tLabel1;
    // End of variables declaration//GEN-END:variables
}
