/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edd.Interfaz;
import java.awt.BorderLayout;
import java.awt.Component;
import javax.swing.*;
import org.graphstream.graph.*;
import org.graphstream.graph.implementations.*;
import org.graphstream.ui.view.*;
import org.graphstream.ui.swing_viewer.SwingViewer;
/**
 * @version /10/2024
 * @author Luigi Lauricella
 */
public class Menu extends JFrame implements ViewerListener {
    private Graph graph;
    private boolean loop = true;

    public Menu() {
        initComponents();
        initGraph(); // Inicializa el grafo
        run(); // Inicia el visualizador
    }

    // Método para inicializar el grafo
    public void initGraph() {
        graph = new SingleGraph("Tutorial 1");

        graph.addNode("A");
        graph.addNode("B");
        graph.addNode("C");
        graph.addEdge("AB", "A", "B");
        graph.addEdge("BC", "B", "C");
        graph.addEdge("CA", "C", "A");

        // Añadir etiquetas para mejor visibilidad
        for (Node node : graph) {
            node.setAttribute("ui.label", node.getId());
        }

        // Estilo predeterminado para los nodos
        graph.setAttribute("ui.stylesheet", "node { fill-color: grey; }");
    }

    // Método para iniciar el bucle del visualizador
    public void run() {
        // Crear un visualizador para el grafo
        var viewer = new SwingViewer(graph, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
        viewer.enableAutoLayout();

        // Crear un pipe del visualizador para manejar clics del ratón
        ViewerPipe fromViewer = viewer.newViewerPipe();
        fromViewer.addViewerListener(this);
        fromViewer.addSink(graph);

        // Añadir el panel del visualizador a jPanel1
        View view = viewer.addDefaultView(false); // Sin vista por defecto
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add((Component)view, BorderLayout.CENTER); // Añadir view al jPanel1

        setVisible(true); // Hacer visible el JFrame

        // Iniciar el bucle de eventos
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() {
                while (loop) {
                    fromViewer.pump(); // Asegurar que se procesan los eventos en un bucle
                }
                return null;
            }
        };
        worker.execute(); // Ejecutar el trabajador en segundo plano
    }

    @Override
    public void viewClosed(String id) {
        loop = false;
    }

    @Override
    public void buttonPushed(String id) {
        System.out.println("Node " + id + " clicked! Toggling color...");
        toggleNodeColor(id); // Cambiar el color del nodo clicado
    }

    @Override
    public void buttonReleased(String id) {
        // Opcional: manejar qué sucede al soltar el botón
    }

    // Método para alternar el color del nodo clicado entre gris y rojo
    private void toggleNodeColor(String nodeId) {
        Node node = graph.getNode(nodeId);
        if (node != null) {
            String currentStyle = String.valueOf(node.getAttribute("ui.style"));
            if (currentStyle.contains("red")) {
                node.setAttribute("ui.style", "fill-color: grey;");
                System.out.println("Node " + nodeId + " color changed to grey.");
            } else {
                node.setAttribute("ui.style", "fill-color: red;");
                System.out.println("Node " + nodeId + " color changed to red.");
            }
        } else {
            System.out.println("Node " + nodeId + " does not exist.");
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseOver(String id) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseLeft(String id) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
